### ISSUE TITLE
style.css missing 'upvotable' and 'disabled' class

### ISSUE THREAD

**Issue by chongman99** [DiscoverMeteor/Microscope#273]
in client/templates/posts/post_item.js, you have:

```javascript
    if (userId && !_.include(this.upvoters, userId)) {
      return 'btn-primary upvotable';
    } else {
      return 'disabled';
```

It looks like you might have dropped the *upvotable* and *disabled* classes from style.css. https://github.com/DiscoverMeteor/Microscope/commit/a6943412644b733ad4e17b3fd3f2c3b01df56bae``

```css
  .post .upvote {
    display: block;
    margin: 7px 12px 0 0;
    float: left; }
```

(Apologies in advance if I am wrong or am looking at the wrong css file to look for those classes)
